[build]
  command = "npm install"
  publish = "."
  functions = "netlify"

[functions]
  node_version = "18" # Você pode ajustar para a versão do Node.js que preferir
  external_node_modules = ["firebase-admin"] # Garante que o firebase-admin seja empacotado com a função